###
## * POWERDNS
#
replicaCount: 1

image:
  repository: discourse/powerdns
  pullPolicy: IfNotPresent
  ### Overrides the image tag whose default is the chart appVersion.
  # tag: ""
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: NodePort
  port: 53

resources: {}
  ### We usually recommend not to specify default resources and to leave this as a conscious
  ### choice for the user. This also increases chances charts run on environments with little
  ### resources, such as Minikube. If you do want to specify resources, uncomment the following
  ### lines, adjust them as necessary, and remove the curly braces after 'resources:'.
resources: {}
# resources:
#   limits:
#     cpu: 100m
#     memory: 128Mi
#   requests:
#     cpu: 100m
#     memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

clusterDomain: cluster.local


###
## ** powerdns
#
powerdns:
  dnssec: true
  config: {}
  # api_key: ""

###
## ** postgresql
#
postgresql:
  postgresqlPostgresPassword: postgres
  postgresqlDatabase: pdns
  postgresqlUsername: pdns
  postgresqlPassword: pdns
  servicePort: 5432
  initdbScriptsConfigMap: initdbscript
  persistence:
    size: 1Gi
  resources: {}
  # resources:
  #   limits:
  #     cpu: 100m
  #     memory: 128Mi
  #   requests:
  #     cpu: 100m
  #     memory: 128Mi


###
## ** powerdnsadmin
#
powerdnsadmin:
  image:
    repository: ngoduykhanh/powerdns-admin
    ### Overrides the image tag whose default is the chart appVersion.
    # tag: ""
    # tag: latest
    tag: 0.2.3
  psqlImage:
    registry: docker.io
    repository: bitnami/postgresql
    tag: 11.10.0-debian-10-r0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9191
  filter: 'basic-auth'                                 ### {'basic-allow'|'basic-auth'|'basic-deny'|'ory'}
  host:
    acmeEmail:            'name@youremail.org'
    certStaging:          false                        ### true: letsencryptStaging; false:letsencrypt
    name: example.org
    namespace: ambassador-hosts
    privateKeySecretName: 'letsencrypt-youremail.org'
  db:
    name: pdnsadmin
  resources: {}
  # resources:
  #   limits:
  #     cpu: 100m
  #     memory: 128Mi
  #   requests:
  #     cpu: 100m
  #     memory: 128Mi

  config:
    user:
      username: 'nick'
      password: '$2y$10$3.XHcaiXtTAXr.tuMOoRfeChYFFA4CMHivTLXHP0YGmV3EblIb1Z6' ### password cf. README.md
      firstname: 'firstname'
      lastname: 'lastname'
      email:    'name@youremail.org'
    setting:
      signup_enabled: false   ### Values: {true|false}



###
## ** configuration of the domain and it's ResourceRecords
#
dns:
  ip: &ip 10.0.0.1
  domains:
    - name: &domainName example.org
      kind: Master
      records:
        nameserver:
          #- name:     "@"
          #  type:     NS
          #  content:  example.org.
          #  ttl:      3600                  ### used for all nameservers (first)
          #  priority: null
          - type:     NS
            content:  ns1.your-provider.org.
            ttl:      3600
          - type:     NS
            content:  ns2.your-provider.org.
            ttl:      3600
        startOfAuthority:
          ttl:         3600
          mname:       example.org.         ### primary
          rname:       dnsadmin.example.org. ### contact
          serial:      ""                   ### set automatically
          refresh:     10800                ### 2ry query -> 1ry after Ns.  86400 (24h)
          retry:       3600                 ### retry after Ns if 1ry does not respond. 7200 (2h)
          expire:      604800               ### 2ry stop delivering after Ns if 1ry does not respond. 3600000 (1000h)
          negativeTTL: 3600                 ### TTL for negative entries
        address:
          - name:     *domainName
            type:     A
            content:  *ip
            ttl:      1800
          - name:     mail.example.org
            type:     A
            content:  *ip
            ttl:      1800
          - name:     "*.example.org"
            type:     A
            content:  *ip
            ttl:      3600
        mailExchange:
          - name:     *domainName
            type:     MX
            content:  "30 mail.example.org."
            ttl:      1800
          - name:     "*.example.org"
            type:     MX
            content:  "30 mail.example.org."
            ttl:      1800
        text:
          - name:     *domainName
            type:     TXT
            content:  "\\\"v=spf1 mx a:mail.example.org -all\\\""
            ttl:      1800
          - name:     _dmarc.example.org
            type:     TXT
            content:  "\\\"v=DMARC1; p=reject; adkim=s; aspf=s\\\""
            ttl:      1800
          - name:     dkim._domainkey.example.org
            type:     TXT
            content:  "\\\"v=DKIM1; k=rsa; p=qwerqwerqwerqwerqwerqwerqwerqwerqwerqwerqwerqwerqwerqwerqwerqwerqwerqwerqwerqwerqwerqwerqwer\\\""
            ttl:      1800
