apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns.fullname" . }}
  labels:
{{ include "powerdns.labels" . | indent 4 }}
type: Opaque
stringData:
  postgres_host:      {{ include "postgresql.dns" .}}
  postgres_port:     "{{ .Values.postgresql.servicePort }}"
  postgres_username: "{{ .Values.postgresql.postgresqlUsername }}"
  postgres_password: "{{ .Values.postgresql.postgresqlPassword }}"
  postgres_database: "{{ .Values.postgresql.postgresqlDatabase }}"
