apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns.fullname" . }}admin
  labels:
{{ include "powerdnsadmin.labels" . | indent 4 }}
type: Opaque
stringData:
  SQLALCHEMY_DATABASE_URI: {{ include "powerdnsadmin.postgresql.dns" . }}
  postgres_database_admin: {{ .Values.powerdnsadmin.db.name }}
