apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "powerdns.fullname" . }}-dns-setup
  labels:
    {{- include "powerdns.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      name: {{ include "powerdns.fullname" . }}-dns-setup
      labels:
        {{- include "powerdns.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: {{ include "powerdns.fullname" . }}admin-db-setup-init
          image: {{ template "psql.imageName" . }}
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          command: [ "bin/sh", "-c", "pg_isready" ]
          env:
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "powerdns.fullname" . }}
                  key: postgres_host
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ include "powerdns.fullname" . }}
                  key: postgres_username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "powerdns.fullname" . }}
                  key: postgres_password
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "powerdns.fullname" . }}
                  key: postgres_database
      containers:
        - name: {{ include "powerdns.fullname" . }}admin-db-setup-main
          image: {{ include "psql.imageName" . }}
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          command: [ "bin/sh", "-c", "./dnsSetup/dnsSetup.sh" ]
          env:
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "powerdns.fullname" . }}
                  key: postgres_host
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ include "powerdns.fullname" . }}
                  key: postgres_username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "powerdns.fullname" . }}
                  key: postgres_password
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "powerdns.fullname" . }}
                  key: postgres_database
          volumeMounts:
           - name: dns-setup
             mountPath: /dnsSetup/
      volumes:
      - name: dns-setup
        projected:
          defaultMode: 0777
          sources:
            - secret:
                name: {{ include "powerdns.fullname" . }}-dns-setup
            - configMap:
                name: {{ include "powerdns.fullname" . }}-dns-setup
      restartPolicy: OnFailure
