apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "powerdns.fullname" . }}-dns-setup
  labels:
{{ include "powerdnsadmin.labels" . | indent 4 }}
data:
  zone.json: |
    {{- range $domain := .Values.dns.domains }}
    {
      "id":   "{{ .name }}.",
      "name": "{{ .name }}.",
      "kind": "{{ .kind }}",
      "nameservers": [
        {{- $nameservers := list -}}
        {{- range $domain.records.nameserver -}}
          {{- $nameservers = printf "\"%s\"" .content | append $nameservers -}}
        {{- end -}}
        {{ $nameservers | join ",\n" | nindent 8}}
      ],
      "soa_edit": "EPOCH",
      "soa_edit_api": "EPOCH"
    }
    {{- end }}
  zoneReverse.json: |
    {{- range $domain := .Values.dns.domains }}
    {
      "id": "{{ include "dns.ip-reverse" $ }}.in-addr.arpa.",
      "name": "{{ include "dns.ip-reverse" $ }}.in-addr.arpa.",
      "kind": "{{ .kind }}",
      "nameservers": [
        {{- $nameservers := list -}}
        {{- range $domain.records.nameserver -}}
          {{- $nameservers = printf "\"%s\"" .content | append $nameservers -}}
        {{- end -}}
        {{ $nameservers | join ",\n" | nindent 8}}
      ],
      "soa_edit": "EPOCH",
      "soa_edit_api": "EPOCH"
    }
    {{- end }}
  rr.json: |
    {
      "rrsets": [
      {{- range $domain := .Values.dns.domains }}
        {
          "comments": [],
          "name": "{{ .name }}.",
          {{- with .records.startOfAuthority }}
          "type": "SOA",
          "ttl": {{ .ttl }},
          "changetype": "REPLACE",
          "records": [
            {
              "content": "{{ .mname }} {{ .rname }} {{ now | unixEpoch }} {{ .refresh }} {{ .retry }} {{ .expire }} {{ .negativeTTL }}",
              "disabled": false
            }
          ]
          {{- end }}
        },
        {
          "name": "thesym.site.",
          "type": "NS",
          {{- with (first .records.nameserver) }}
          "ttl": {{ .ttl }},
          {{- end }}
          "changetype": "REPLACE",
          "records": [
            {{- $nameservers := list -}}
            {{- range $domain.records.nameserver -}}
              {{- $nameservers = printf "{\n  \"content\": \"%s\",\n  \"disabled\": false\n}" .content | append $nameservers -}}
            {{- end -}}
            {{ $nameservers | join ",\n" | nindent 12 }}
          ]
        },
        {{- /* create the {A,MX,TXT}-RR */}} 
	  {{- $A_RR   := list -}}
	  {{- $MX_RR  := list -}}
	  {{- $TXT_RR := list -}}
          {{- range $domain.records.address      -}} {{- $A_RR   = (include "dns.record-template" . ) | append $A_RR   -}} {{- end -}}
	  {{- range $domain.records.mailExchange -}} {{- $MX_RR  = (include "dns.record-template" . ) | append $MX_RR  -}} {{- end -}}
	  {{- range $domain.records.text         -}} {{- $TXT_RR = (include "dns.record-template" . ) | append $TXT_RR -}} {{- end -}}
        {{- /* insert the RR */}} 
	  {{- $A_RR   | join ",\n" | nindent 8 -}},
	  {{- $MX_RR  | join ",\n" | nindent 8 -}},
	  {{- $TXT_RR | join ",\n" | nindent 8 -}}
      {{- end }}
      ]
    }
  rrReverse.json: |
    {
      "rrsets": [
        {
          "comments": [],
          "name": "{{ include "dns.ip-reverse" .}}.in-addr.arpa.",
          "type": "SOA",
          "ttl": 3600,
          "changetype": "REPLACE",
          "records": [
            {
              "content": "ns1.domain.com. dnsadmin.domain.com. 2019090253 10800 3600 604800 3600",
              "disabled": false
            }
          ]
        },
        {
          "name": "{{ include "dns.ip-reverse" .}}.in-addr.arpa.",
          "type": "PTR",
          "ttl": 1800,
          "changetype": "REPLACE",
          "records": [
            {
              "content": "thesym.site.",
              "disabled": false
            }
          ]
        }
      ]
    }
