apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns.fullname" . }}-dns-setup
  labels:
{{ include "powerdnsadmin.labels" . | indent 4 }}
type: Opaque
stringData:
  1-dnsSetup.sh: |
    curl -sH 'X-API-Key: {{ .Values.powerdns.api_key }}' powerdns-webserver.powerdns/api/v1/servers
    curl -X POST -s -H 'X-API-Key: daeThaiNg0oShibaV7Shair1' \
        powerdns-webserver.powerdns/api/v1/servers/localhost/zones \
        -d '
          {
                  "id": "thesym.site.",
                  "name": "thesym.site.",
                  "kind": "Master",
                  "nameservers": [],
                  "records": [
                          {
                                  "content": "thesym.site",
                                  "disabled": false,
                                  "name": "thesym.site",
                                  "ttl": 5,
                                  "type": "NS"
                          },
                          {
                                  "content": "ns1.domain.com",
                                  "disabled": false,
                                  "name": "ns1.domain.com",
                                  "ttl": 5,
                                  "type": "NS"
                          },
                          {
                                  "content": "ns2.domain.com",
                                  "disabled": false,
                                  "name": "ns2.domain.com",
                                  "ttl": 5,
                                  "type": "NS"
                          },
                          {
                                  "content": "thesym.site. domainadmin.thesym.site. 1 1800 900 604800 86400",
                                  "disabled": false,
                                  "type": "SOA",
                                  "ttl": 25,
                                  "name": "thesym.site"
                          }
                ]
        }'

