apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns.fullname" . }}-dns-setup
  labels:
{{ include "powerdnsadmin.labels" . | indent 4 }}
type: Opaque
stringData:
  1-dnsSetup.sh: |
    curl -sH 'X-API-Key: {{ .Values.powerdns.api_key }}' powerdns-webserver.powerdns/api/v1/servers
