apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns.fullname" . }}-dns-setup
  labels:
{{ include "powerdnsadmin.labels" . | indent 4 }}
type: Opaque
stringData:
  dnsSetup.sh: |
    ###
    ## * dnsSetup (truncate DB and create via the API)
    #
    psql -a \
      -c "TRUNCATE TABLE comments       CASCADE;" \
      -c "TRUNCATE TABLE cryptokeys     CASCADE;" \
      -c "TRUNCATE TABLE domainmetadata CASCADE;" \
      -c "TRUNCATE TABLE domains        CASCADE;" \
      -c "TRUNCATE TABLE records        CASCADE;" \
      -c "TRUNCATE TABLE supermasters   CASCADE;" \
      -c "TRUNCATE TABLE tsigkeys       CASCADE;"


    BASE_DIR=$(dirname $0:h:P)

    ###
    ## ** create the zone
    #
    curl -s \
      -X POST \
      -H "X-API-Key: {{ .Values.powerdns.api_key }}" \
      -d "@${BASE_DIR}/zone.json" \
      powerdns-webserver.powerdns/api/v1/servers/localhost/zones

    ###
    ## ** create all resourceRecords in the zone
    #
    curl -s \
      -X PATCH \
      -H "X-API-Key: {{ .Values.powerdns.api_key }}" \
      -H "content-type: application/json" \
      -d "@${BASE_DIR}/rr.json" \
      powerdns-webserver.powerdns/api/v1/servers/localhost/zones/thesym.site


    ###
    ## ** create the reverse Zone for the PTR
    #
    curl -s \
      -X POST \
      -H "X-API-Key: {{ .Values.powerdns.api_key }}" \
      -d "@${BASE_DIR}/zoneReverse.json" \
      powerdns-webserver.powerdns/api/v1/servers/localhost/zones


    ###
    ## ** create all resourceRecords in the reverse zone
    #
    curl -s \
      -X PATCH \
      -H "X-API-Key: {{ .Values.powerdns.api_key }}" \
      -H "content-type: application/json" \
      -d "@${BASE_DIR}/rrReverse.json" \
      powerdns-webserver.powerdns/api/v1/servers/localhost/zones/169.207.93.in-addr.arpa


    ###
    ## ** DEBUG: print all records
    #
    # curl -s \
    #   -X GET \
    #   -H "X-API-Key: {{ .Values.powerdns.api_key }}" \
    #   powerdns-webserver.powerdns/api/v1/servers/localhost/zones/thesym.site
    # curl -s \
    #   -X GET \
    #   -H "X-API-Key: {{ .Values.powerdns.api_key }}" \
    #   powerdns-webserver.powerdns/api/v1/servers/localhost/zones/169.207.93.in-addr.arpa
