{{ if false }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns.fullname" . }}dns-setup
  labels:
{{ include "powerdnsadmin.labels" . | indent 4 }}
type: Opaque
stringData:
  1-DNS.sql: |
{{ end }}
